version: "3.8"
services:
  docker:
    image: docker:dind
    ports:
      - 8080:8080
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
  jenkins:
    image: jenkins/jenkins:2.303.1-lts-jdk11
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
